# Generated by Django 5.0.2 on 2024-04-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='phprice',
            new_name='price',
        ),
    ]
